/* AUTOGENERATED FILE - DO NOT EDIT CONTENTS */

export const projectId = "nanyeperznosnxqbawvf"
export const publicAnonKey = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im5hbnllcGVyem5vc254cWJhd3ZmIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NzA5OTk4MjUsImV4cCI6MjA4NjU3NTgyNX0.BfI4DMbJHWqloBfX1mv4hqz73tFh0-qtKzzqQDHIfDY"
